## Filament Spreadsheet Grid (asignua/filament-spreadsheet-grid)

- Excel-style editing of a Filament table. Three parts, all required: `use Asignua\FilamentSpreadsheetGrid\Concerns\InteractsWithSpreadsheetGrid;` on the Livewire component that owns the table (List page, relation manager, table widget), `Asignua\FilamentSpreadsheetGrid\Columns\GridColumn` instead of the plain column, and `->header(SpreadsheetGrid::toolbar())` on the table. Without the toolbar the cells render but are inert.
- `GridColumn::make('price')->number(min: 0)` / `->integer()` / `->select([...] | Enum::class)` / `->date('d.m.Y')` / `->boolean()` / default text. `->required()`, `->maxLength()`, `->rules([...] | fn (Model $record) => [...])`, `->editable(bool | Closure)`, `->emptyAs(mixed)` (an emptied cell is `null` otherwise). Numbers and decimals reach the model as numeric strings, integers as int.
- Configure the grid by overriding `protected function spreadsheetGrid(SpreadsheetGrid $grid): SpreadsheetGrid` on the component: `->saveUsing(fn (Model $record, array $changes) => ...)`, `->authorizeUsing(fn (Model $record): bool => ...)`, `->atomic()`, `->autosave()`, `->maxRows()`, `->notify(false)`.
- The default write path is explicit `setAttribute()` + `save()` (no mass assignment). Apps with repositories / DTOs must use `saveUsing`; it gets the record and the validated, typed `[column => value]` of ONE row and may throw `ValidationException` (shown on the named cells). A dotted column name needs `saveUsing`, otherwise a `LogicException` is thrown.
- Saves go through the table's BASE query (`getEloquentQuery()`, tenant scopes) plus Filament's own edit gate (the resource's `canEdit()`, a relation manager's `canEdit()` / read-only state on View pages, else the `update` policy, honouring `strictAuthorization()`); user filters and search are not applied. Hidden columns (`->visible()` / `->hidden()`) are not writable. Never write your own endpoint for the grid: `saveSpreadsheetGrid()` is the only one.
- `->toggleable(default: false, persist: false)` adds an "Edit as spreadsheet" switch: while off, grid columns are plain text (so `recordUrl()` works) and saves are refused. This is UX, not access control: guard writes with authorization. Without it the grid is always editable.
- Do not combine with `recordUrl()` / `recordAction()`; pivot-keyed relation tables are unsupported.
- Assets are compiled and committed in `resources/dist` (`npm run build` after changing `resources/js` or `resources/css`); run `php artisan filament:assets` after install.
